const FETCH_USER_ACCOUNTS = 'FETCH_USER_ACCOUNTS';
const FETCH_REPORTS = 'FETCH_REPORTS';
const MANAGE_USER_ACCOUNT = 'MANAGE_USER_ACCOUNT';
const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_USER_ACCOUNTS,
  FETCH_REPORTS,
  MANAGE_USER_ACCOUNT,
  DELETE_USER_ACCOUNT,
  CLEAR_ALL,
};
