const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const SAVE_EXPIRATION_DATE_TOKEN = 'SAVE_EXPIRATION_DATE_TOKEN';
const UPDATE_TOKEN = 'UPDATE_TOKEN';
const REMEMBER_USER = 'REMEMBER_USER';
const LOGOUT_USER = 'LOGOUT_USER';

export default {
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  UPDATE_TOKEN,
  SAVE_EXPIRATION_DATE_TOKEN,
  REMEMBER_USER,
  LOGOUT_USER,
};
