const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const SAVE_EXPIRATION_DATE_TOKEN = 'SAVE_EXPIRATION_DATE_TOKEN';
const UPDATE_TOKEN = 'UPDATE_TOKEN';
const REMEMBER_USER = 'REMEMBER_USER';
const SAVE_LOGGED_USER_PROFILE = 'SAVE_LOGGED_USER_PROFILE';
const SAVE_LOGGED_USER_FRIENDS = 'SAVE_LOGGED_USER_FRIENDS';
const SAVE_LOGGED_USER_FRIEND_INVITATIONS =
  'SAVE_LOGGED_USER_FRIEND_INVITATIONS';
const LOG_OUT_USER = 'LOG_OUT_USER';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  UPDATE_TOKEN,
  SAVE_EXPIRATION_DATE_TOKEN,
  REMEMBER_USER,
  SAVE_LOGGED_USER_PROFILE,
  SAVE_LOGGED_USER_FRIENDS,
  SAVE_LOGGED_USER_FRIEND_INVITATIONS,
  LOG_OUT_USER,
  CLEAR_ALL,
};
