const SAVE_ACCESS_TOKEN = 'SAVE_ACCESS_TOKEN';
const SAVE_REFRESH_TOKEN = 'SAVE_REFRESH_TOKEN';
const SAVE_USER_ID = 'SAVE_USER_ID';
const SAVE_EXPIRATION_DATE_TOKEN = 'SAVE_EXPIRATION_DATE_TOKEN';
const LOGOUT_USER = 'LOGOUT_USER';

export default {
  SAVE_ACCESS_TOKEN,
  SAVE_REFRESH_TOKEN,
  SAVE_USER_ID,
  SAVE_EXPIRATION_DATE_TOKEN,
  LOGOUT_USER,
};
