const FETCH_USER_CHATS = 'FETCH_USER_CHATS';
const FETCH_CHAT_DETAILS = 'FETCH_CHAT_DETAILS';
const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';

export default {
  FETCH_USER_CHATS,
  FETCH_CHAT_DETAILS,
  ADD_NEW_MESSAGE,
};
