const FETCH_USER_CHATS = 'FETCH_USER_CHATS';
const FETCH_CHAT_DETAILS = 'FETCH_CHAT_DETAILS';
const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
const EDIT_MESSAGE = 'EDIT_MESSAGE';
const DELETE_MESSAGE = 'DELETE_MESSAGE';
const CHANGE_MEMBER_PERMISSION = 'CHANGE_MEMBER_PERMISSION';
const DELETE_MEMBER = 'DELETE_MEMBER';
const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
const ADD_TYPING_MESSAGE = 'ADD_TYPING_MESSAGE';
const DELETE_TYPING_MESSAGE = 'DELETE_TYPING_MESSAGE';
const UPDATE_CHAT_MEMBERS = 'UPDATE_CHAT_MEMBERS';

export default {
  FETCH_USER_CHATS,
  FETCH_CHAT_DETAILS,
  ADD_NEW_MESSAGE,
  EDIT_MESSAGE,
  DELETE_MESSAGE,
  CHANGE_MEMBER_PERMISSION,
  DELETE_MEMBER,
  SET_ACTIVE_CHAT,
  ADD_TYPING_MESSAGE,
  DELETE_TYPING_MESSAGE,
  UPDATE_CHAT_MEMBERS,
};
