const FETCH_EVENTS = 'FETCH_EVENTS';
const FETCH_EVENT_DETAILS = 'FETCH_EVENT_DETAILS';
const FETCH_EVENT_INVITATIONS = 'FETCH_EVENT_INVITATIONS';
const UPDATE_RESPOND_TO_EVENT = 'UPDATE_RESPOND_TO_EVENT';
const RESPOND_TO_EVENT = 'RESPOND_TO_EVENT';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_EVENTS,
  FETCH_EVENT_DETAILS,
  FETCH_EVENT_INVITATIONS,
  UPDATE_RESPOND_TO_EVENT,
  RESPOND_TO_EVENT,
  CLEAR_ALL,
};
