const FETCH_EVENTS = 'FETCH_EVENTS';
const FETCH_EVENT_INVITATIONS = 'FETCH_EVENT_INVITATIONS';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_EVENTS,
  FETCH_EVENT_INVITATIONS,
  CLEAR_ALL,
};
