const FETCH_USER_FRIENDS_SUGGESTIONS = 'FETCH_USER_FRIENDS_SUGGESTIONS';
const FETCH_LOGGED_USER_FRIENDS = 'FETCH_LOGGED_USER_FRIENDS';
const FETCH_LOGGED_USER_RECEIVED_FRIEND_INVITATIONS =
  'FETCH_LOGGED_USER_RECEIVED_FRIEND_INVITATIONS';
const FETCH_LOGGED_USER_SENT_FRIEND_INVITATIONS =
  'FETCH_LOGGED_USER_SENT_FRIEND_INVITATIONS';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_USER_FRIENDS_SUGGESTIONS,
  FETCH_LOGGED_USER_FRIENDS,
  FETCH_LOGGED_USER_RECEIVED_FRIEND_INVITATIONS,
  FETCH_LOGGED_USER_SENT_FRIEND_INVITATIONS,
  CLEAR_ALL,
};
