const FETCH_GROUPS = 'FETCH_GROUPS';
const FETCH_GROUP_DETAILS = 'FETCH_GROUP_DETAILS';
const FETCH_GROUP_INVITATIONS = 'FETCH_GROUP_INVITATIONS';
const FETCH_USER_GROUP_JOIN_REQUESTS = 'FETCH_USER_GROUP_JOIN_REQUESTS';
const FETCH_GROUP_POSTS = 'FETCH_GROUP_POSTS';

export default {
  FETCH_GROUPS,
  FETCH_GROUP_DETAILS,
  FETCH_GROUP_INVITATIONS,
  FETCH_USER_GROUP_JOIN_REQUESTS,
  FETCH_GROUP_POSTS,
};
