const CREATE_POST = 'CREATE_POST';
const LIKE_POST = 'LIKE_POST';
const DISLIKE_POST = 'DISLIKE_POST';
const COMMENT_POST = 'COMMENT_POST';
const EDIT_POST_COMMENT = 'EDIT_POST_COMMENT';
const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT';
const LIKE_POST_COMMENT = 'LIKE_POST_COMMENT';
const DISLIKE_POST_COMMENT = 'DISLIKE_POST_COMMENT';

export default {
  CREATE_POST,
  LIKE_POST,
  DISLIKE_POST,
  COMMENT_POST,
  EDIT_POST_COMMENT,
  DELETE_POST_COMMENT,
  LIKE_POST_COMMENT,
  DISLIKE_POST_COMMENT,
};
