const CREATE_POST = 'CREATE_POST';
const EDIT_POST = 'EDIT_POST';
const DELETE_POST = 'DELETE_POST';
const LIKE_POST = 'LIKE_POST';
const DISLIKE_POST = 'DISLIKE_POST';
const COMMENT_POST = 'COMMENT_POST';
const EDIT_POST_COMMENT = 'EDIT_POST_COMMENT';
const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT';
const LIKE_POST_COMMENT = 'LIKE_POST_COMMENT';
const DISLIKE_POST_COMMENT = 'DISLIKE_POST_COMMENT';
const POST_ACCESS = 'POST_ACCESS';
const POST_COMMENTS_ACCESS = 'POST_COMMENTS_ACCESS';
const SHARE_POST = 'SHARE_POST';
const UPDATE_SHARED_POST = 'UPDATE_SHARED_POST';
const DELETE_SHARED_POST = 'DELETE_SHARED_POST';

export default {
  CREATE_POST,
  EDIT_POST,
  DELETE_POST,
  LIKE_POST,
  DISLIKE_POST,
  COMMENT_POST,
  EDIT_POST_COMMENT,
  DELETE_POST_COMMENT,
  LIKE_POST_COMMENT,
  DISLIKE_POST_COMMENT,
  POST_ACCESS,
  POST_COMMENTS_ACCESS,
  SHARE_POST,
  UPDATE_SHARED_POST,
  DELETE_SHARED_POST,
};
