const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';
const FETCH_ALL_USERS_INFORMATION = 'FETCH_ALL_USERS_INFORMATION';
const FETCH_ACTIVITY_NOTIFICATIONS = 'FETCH_ACTIVITY_NOTIFICATIONS';
const SET_LOADING = 'SET_LOADING';
const CLEAR_ALL = 'CLEAR_ALL';
const SET_NOTIFICATION_STOMP = 'SET_NOTIFICATION_STOMP';

export default {
  FETCH_BOARD_SUCCESS,
  FETCH_BOARD_FAILURE,
  FETCH_ALL_USERS_INFORMATION,
  FETCH_ACTIVITY_NOTIFICATIONS,
  SET_LOADING,
  CLEAR_ALL,
  SET_NOTIFICATION_STOMP,
};
