const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_BOARD_SUCCESS,
  FETCH_BOARD_FAILURE,
  CLEAR_ALL,
};
