const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
const FETCH_USER_ACTIVITY = 'FETCH_USER_ACTIVITY';
const FETCH_USER_FAVOURITES = 'FETCH_USER_FAVOURITES';
const FETCH_POSSIBLE_INTERESTS = 'FETCH_POSSIBLE_INTERESTS';
const FETCH_USER_INTERESTS = 'FETCH_USER_INTERESTS';
const FETCH_USER_IMAGES = 'FETCH_USER_IMAGES';
const FETCH_USER_FRIENDS = 'FETCH_USER_FRIENDS';
const FETCH_USER_FRIENDS_INVITATION = 'FETCH_USER_FRIENDS_INVITATION';
const SET_PROFILE_NAV_INDEX = 'SET_PROFILE_NAV_INDEX';
const FETCH_USER_GROUPS = 'FETCH_USER_GROUPS';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_USER_PROFILE,
  FETCH_USER_ACTIVITY,
  FETCH_USER_FAVOURITES,
  FETCH_POSSIBLE_INTERESTS,
  FETCH_USER_INTERESTS,
  FETCH_USER_IMAGES,
  FETCH_LOGGED_USER_FRIENDS: FETCH_USER_FRIENDS,
  FETCH_USER_FRIENDS_INVITATION,
  SET_PROFILE_NAV_INDEX,
  FETCH_USER_GROUPS,
  CLEAR_ALL,
};
