const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
const FETCH_USER_ACTIVITY = 'FETCH_USER_ACTIVITY';
const FETCH_USER_FAVOURITES = 'FETCH_USER_FAVOURITES';
const FETCH_POSSIBLE_INTERESTS = 'FETCH_POSSIBLE_INTERESTS';
const FETCH_USER_INTERESTS = 'FETCH_USER_INTERESTS';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_USER_PROFILE,
  FETCH_USER_ACTIVITY,
  FETCH_USER_FAVOURITES,
  FETCH_POSSIBLE_INTERESTS,
  FETCH_USER_INTERESTS,
  CLEAR_ALL,
};
