const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
const FETCH_USER_ACTIVITY = 'FETCH_USER_ACTIVITY';
const CLEAR_ALL = 'CLEAR_ALL';

export default {
  FETCH_USER_PROFILE,
  FETCH_USER_ACTIVITY,
  CLEAR_ALL,
};
